if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
	source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


#||||||||||||||||||||||||| ENVIRONMENT VARIABLES ||||||||||||||||||||||||||||||

#export ARCHFLAGS="-arch x86_64"
export ZSH="$HOME/.oh-my-zsh"
export ZSH_CUSTOM="$ZSH/custom"
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.dotnet/tools:$PATH"
export XDG_CONFIG_HOME="$HOME/.config"
export MANPATH="/usr/local/man:$MANPATH"
export LANG=en_US.UTF-8
export EDITOR="nvim"
export SUDO_PROMPT="%{$fg[yellow]󰌾 %} Password: "

# |||||||||||||||||||||||||||| CONFIGURATION ||||||||||||||||||||||||||||||||||

ZSH_THEME="powerlevel10k/powerlevel10k"

#ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell`" "agnoster" )

POWERLEVEL_LEGACY_ICON_SPACING="true"

ZLE_RPROMPT_INDENT=0

CASE_SENSITIVE="true"

HYPHEN_INSENSITIVE="true"

DISABLE_MAGIC_FUNCTIONS="false"

DISABLE_LS_COLORS="false"

DISABLE_AUTO_TITLE="false"

ENABLE_CORRECTION="true"

# COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"

COMPLETION_WAITING_DOTS="true"

DISABLE_UNTRACKED_FILES_DIRTY="false"

HIST_STAMPS="mm/dd/yyyy"

# zstyle ':omz:update' mode reminder
# zstyle ':omz:update' mode disabled
zstyle ':omz:update' mode auto
zstyle ':omz:update' frequency 13

# ||||||||||||||||||||||||||||||||| PLUGINS |||||||||||||||||||||||||||||||||||

plugins=(
#   adb
    alias-finder
    aliases
    autopep8
    colored-man-pages
#   emoji
    emotty
    genpass
    git
    python
#   ripgrep
    sudo
    vi-mode
    web-search
    z
    zbell
    zsh-interactive-cd
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh
source $ZSH_CUSTOM/plugins

lsu () {
	if [[ (-d $1 && ! -w $1) || ! -w $1 ]]; then
		echo "Permission denied to write \'$!\'"
	elif [[ -d $1 && (-w $1 || -r $1) ]]; then
		lsd -la $1
	elif [[ -w $1 && ! -d $1 ]]; then
		nvim $1
	else
		echo "done"
	fi
}

xred () {
	sync
	if [[ ! -w $1 || ( -d $1 && ! -w $1 ) ]]; then
		echo "Permission denied!"
		exit
	elif [[ -d $1 ]]; then
		find $1 -type f | xargs scrub -Sfp usarmy > /dev/null 2>&1
		find $1 -type f | xargs shred -fn 32 -zux
		rm -drf $1
		echo "All clean!\n"
	else
		scrub -fp usarmy $1 > /dev/null 2>&1
		shred -fn 32 -zux $1
		echo "All clean!\n"
	fi
}

nv () {
	if [[ -w $1 ]]; then
		nvim $1
	elif [[ -a $1 ]]; then
		sudo nvim $1
	else
		touch $1; nvim $1
	fi
}

# ___________________________ ALIASSES ________________________________________
alias ..="cd .."
alias cwork="cd ~/Documents/Workspaces"
alias cdown="cd ~/Downloads"
alias cdoc="cd ~/Documents"
alias cdesk="cd ~/Desktop"
alias cpic="cd ~/Pictures"
alias cvid="cd ~/Videos"
alias cmus="cd ~/Music"
alias ll="lsd -lh"
alias la="lsd -lah"
alias llr="lsd -R"
alias rmdr="rm -drf"
alias imgk="kitty +kitten icat"
alias imgw="wezterm imgcat"

# __________________________ UPDATES ________________________________
alias src="source ~/.zshrc"
alias upfont="fc-cache -fv"
alias upgrub="sudo grub-mkconfig -o /boot/grub/grub.cfg"
alias upsys="sudo pacman -Syu"

# __________________________ CONFIGURATION FILES ________________________________
alias cfgzs="nvim ~/.zshrc"
alias cfgp10="nvim ~/.p10k.zsh"
alias cfgwz="nvim ~/.config/wezterm/wezterm.lua"
alias cfgaw="nvim ~/.config/awesome/rc.lua"
alias addr="ip addr"

# __________________________ PACKAGES ________________________________
alias parus="paru -Ss"
alias parui="paru -S"
alias pacs="pacman -Ss"
alias paci="sudo pacman -S"
#alias pacr="sudo pacman -Rcu"
#alias purge="sudo pacman -Rcc $(pacman -Quq)"

# __________________________ Git (common repo) ________________________________
alias gitdot="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
alias dota="gitdot add"
alias dotb="gitdot branch"
alias dotc="gitdot commit -m"
alias dotd="gitdot diff"
alias dotl="gitdot log"
alias dotlo="gitdot log --oneline"
alias dotlogr='gitdot log --all --decorate --oneline --graph'
alias dotm="gitdot merge"
alias dotp="gitdot push"
alias dotpl="gitdot pull"
alias dotr="gitdot remote"
alias dotre="gitdot reset"
alias dots="gitdot checkout"
alias dotst="gitdot status"

# __________________________ Git (bare repo dotfiles) __________________________
alias gita="git add"
alias gitb="git branch"
alias gitc="git commit -m"
alias gitd="git diff"
alias gitl="git log"
alias gitlo="git log --oneline"
alias gitlogr='git log --all --decorate --oneline --graph'
alias gitm="git merge"
alias gitp="git push"
alias gitpl="git pull"
alias gitr="git remote"
alias gitre="git reset"
alias gitch="git checkout"
alias gitst="git status"
alias gitsw="git switch"
alias gitf="git fetch"
alias gitcl="git clone"

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
